development:
  adapter: async

test:
  adapter: test

production:
  adapter: <%= ENV["REDIS_URL"].present? ? "redis" : "postgresql" %>
  url: <%= ENV["REDIS_URL"] if ENV["REDIS_URL"].present? %>
  channel_prefix: hobo_
